# Generated by Django 4.2.4 on 2023-08-24 14:42

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122, null=True, verbose_name='Full Name')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='Profile Picture')),
                ('details', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Short Summary')),
                ('email', models.CharField(max_length=122, null=True)),
                ('phone', models.CharField(blank=True, max_length=122, null=True)),
                ('link_git', models.URLField(blank=True, default='#', null=True, verbose_name='Github Link')),
                ('link_li', models.URLField(blank=True, default='#', null=True, verbose_name='Linkedin Link')),
                ('link_fb', models.URLField(blank=True, default='#', null=True, verbose_name='Facebook Link')),
                ('link_insta', models.URLField(blank=True, default='#', null=True, verbose_name='Instagram Link')),
                ('resume', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Information',
                'verbose_name_plural': 'Informations',
                'ordering': ['-id'],
            },
        ),
    ]
