# Generated by Django 4.2.4 on 2023-08-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsQualificationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=555, null=True, verbose_name='Add Field')),
            ],
            options={
                'verbose_name': 'Skill & Qualification',
                'verbose_name_plural': 'Skills & Qualifications',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='infomodel',
            name='link_fb',
            field=models.URLField(blank=True, default='https://www.google.com/', null=True, verbose_name='Facebook Link'),
        ),
        migrations.AlterField(
            model_name='infomodel',
            name='link_git',
            field=models.URLField(blank=True, default='https://www.google.com/', null=True, verbose_name='Github Link'),
        ),
        migrations.AlterField(
            model_name='infomodel',
            name='link_insta',
            field=models.URLField(blank=True, default='https://www.google.com/', null=True, verbose_name='Instagram Link'),
        ),
        migrations.AlterField(
            model_name='infomodel',
            name='link_li',
            field=models.URLField(blank=True, default='https://www.google.com/', null=True, verbose_name='Linkedin Link'),
        ),
    ]
