# Generated by Django 4.2.4 on 2023-08-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_skillsqualificationsmodel_alter_infomodel_link_fb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=555, null=True, verbose_name='Add Field')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TechStackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=555, null=True, verbose_name='Add Field')),
            ],
            options={
                'verbose_name': 'Tech Stack',
                'verbose_name_plural': 'Tech Stacks',
                'ordering': ['-id'],
            },
        ),
    ]
