# Generated by Django 4.2.4 on 2023-08-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_educationsmodel_techstackmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=555, null=True, verbose_name='Paper Title')),
                ('link', models.URLField(blank=True, default='https://www.google.com/', null=True, verbose_name='Add Link')),
            ],
            options={
                'verbose_name': 'Publication & Award',
                'verbose_name_plural': 'Publication & Awards',
                'ordering': ['-id'],
            },
        ),
    ]
