# Generated by Django 4.2.4 on 2023-08-30 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_worksmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomodel',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='Resume-files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Resume'),
        ),
    ]
